version: "3.9"

services:
  dm-cadquery:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/dm-cadquery/Dockerfile
    volumes:
      - .:/app

  dm-openscad:
    build:
      context: .
      dockerfile: docker/dm-openscad/Dockerfile
    volumes:
      - .:/app